### ISSUE TITLE
[Feature] Postgres Compatibility

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_intercom_source#16]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

This package is currently only compatible with Redshift, Snowflake, and BigQuery. It would be great to add support for Postgres.

### Describe alternatives you've considered

This package _may_ be compatible with PostgreSQL. However, official support and update of our integration tests would be ideal.

### Are you interested in contributing this feature?

- [x] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

### Anything else?

If anyone comes across this feature and would like more eyes on it 👀 . Please comment below and we can prioritize it!

**Comment by fivetran-avinash** [comment]
These changes will now be reflected the v0.5.0 release of `dbt_intercom`. See above for details about the feature pull requests!
