### ISSUE TITLE
bug on some fields history models + missing SLA variables

### ISSUE THREAD

**Issue by ant0inemtr** [fivetran/dbt_intercom_source#2]
Hi ! Fivetran customer, currently testing your great dbt packages on Jira and Intercom 😄.

1°) 
It seems that there is the same bug in two of your models:
- stg_intercom__company_history
- stg_intercom__contact_history

If we take stg_intercom__company_history as an example, we have this error:
`Database Error in model stg_intercom__company_history (models/stg_intercom__company_history.sql)
  column reference "plan_name" is ambiguous
  compiled SQL at target/run/intercom_source/models/stg_intercom__company_history.sql`

Indeed, get_company_history_columns refers to multiple fields:
`   {"name": "_fivetran_deleted", "datatype": "boolean"},
    {"name": "_fivetran_synced", "datatype": dbt_utils.type_timestamp()},
    {"name": "company_id", "datatype": dbt_utils.type_string()},
    {"name": "created_at", "datatype": dbt_utils.type_timestamp()},
    {"name": "id", "datatype": dbt_utils.type_string()},
    {"name": "industry", "datatype": dbt_utils.type_int()},
    {"name": "last_request_at", "datatype": dbt_utils.type_timestamp()},
    {"name": "monthly_spend", "datatype": dbt_utils.type_int()},
    {"name": "name", "datatype": dbt_utils.type_string()},
    {"name": "plan_id", "datatype": dbt_utils.type_int()},
    {"name": "plan_name", "datatype": dbt_utils.type_int()},
    {"name": "remote_created_at", "datatype": dbt_utils.type_timestamp()},
    {"name": "session_count", "datatype": dbt_utils.type_int()},
    {"name": "size", "datatype": dbt_utils.type_int()},
    {"name": "updated_at", "datatype": dbt_utils.type_timestamp()},
    {"name": "user_count", "datatype": dbt_utils.type_int()},
    {"name": "website", "datatype": dbt_utils.type_int()}`

The problem is that in your subquery named final, you only select some of the fields above. For instance, **plan_id** and **plan_name** are not in this SELECT. This is the same problem for other variables above not in the final subquery's SELECT.

Let's say I want to include these fields. I'd try to add them into the `company_history_pass_through_columns` array. However, this is triggering an error when running stg_intercom__company_history model, because in the `fields` subquery, you'd get 2 times plan_name and plan_id: one time because of the fivetran_utils.fill_staging_columns (through get_company_history_columns), and one more time because of company_history_pass_through_columns --> dbt error.

This is the same issue with stg_intercom__contact_history because of the get_contact_history_columns vs. final subquery.

So I think either:
- the concerned variables (plan_id, plan_name and some other ones) must be deleted from get_company_history_columns and you keep the final subquery like this
or
- you don't edit the get_company_history_columns and you add the concerned variables in the final subquery.

Hope it's really a bug and not some misunderstanding from me 😆

2°) It's not a bug, but it seems that `sla_name` and `sla_status` are not taken from `conversation_history` in your models. It'd be awesome to include these two variables, not only in dbt_intercom_source, but also in dbt_intercom, as they are definitely key metrics for conversations.

Thank you in advance and sorry for this loooong message!
Antoine

**Comment by fivetran-kristin** [comment]
hey @ant0inemtr thanks for bringing this up! We're working on a fix now and will let you know when the changes are ready.

**Comment by fivetran-joemarkiewicz** [comment]
Hey @ant0inemtr we have been able to release a new version of the Intercom packages to the dbt hub with the fixes you mentioned in this issue as well as some other enhancements! You can find the updated packages in the below links:
- [dbt_intercom_source](https://hub.getdbt.com/fivetran/intercom_source/latest/)
- [dbt_intercom](https://hub.getdbt.com/fivetran/intercom/latest/)

Thanks again for bringing this bug to our attention, and happy dbt'ing!
