### ISSUE TITLE
[Feature] Add combination of column tests to history tables

### ISSUE THREAD

**Issue by fivetran-catfritz** [fivetran/dbt_intercom_source#32]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Continuing from #30, we had to remove a uniqueness test in #31 from a history table, however it was an interim fix. We need to revise the tests for the history tables to add combination of column or surrogate key tests. We still want to test uniqueness, however at the appropriate level. 

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Closing this as the issue has already been addressed
