### ISSUE TITLE
[Feature] update/remove calogica

### ISSUE THREAD

**Issue by fivetran-catfritz** [fivetran/dbt_intercom_source#35]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Uses the old version. Causes version conflicts.

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
This has been addressed in the latest v0.8.0 release
